import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { augmentRoleLibrary, type RoleLibraryJob } from "@shared/matcher";
import { storage } from "./storage";
import { syncedRoleToLibraryJob } from "./role-sync";
// Statically import the role library + summaries so esbuild bundles them into
// the production server build. The dev server also reads the files from disk
// as a fallback so regenerating the JSON without restarting works.
import BUNDLED_LIBRARY from "../shared/role-library.json";
import BUNDLED_SUMMARIES from "../shared/role-summaries.json";

function _dirname(): string {
  try {
    // CJS at runtime
    // @ts-ignore
    if (typeof __dirname !== "undefined") return __dirname as unknown as string;
  } catch {}
  try {
    return path.dirname(fileURLToPath(import.meta.url));
  } catch {
    return process.cwd();
  }
}

function loadSharedJson<T>(fileName: string, bundled: T): T {
  const candidates = [
    path.resolve(process.cwd(), `shared/${fileName}`),
    path.resolve(_dirname(), `../shared/${fileName}`),
    path.resolve(_dirname(), `../../shared/${fileName}`),
  ];
  for (const p of candidates) {
    try {
      if (fs.existsSync(p)) {
        return JSON.parse(fs.readFileSync(p, "utf-8"));
      }
    } catch {}
  }
  return bundled;
}

// Read the role library JSON once at startup. We bundle a snapshot under
// shared/role-library.json. The build script (scripts/build-role-library.ts)
// regenerates it from the source .txt files.
function loadLibrary(): { generated_at: string; jobs: RoleLibraryJob[] } {
  const loaded = loadSharedJson<{ generated_at: string; jobs: RoleLibraryJob[] } | null>(
    "role-library.json",
    BUNDLED_LIBRARY as { generated_at: string; jobs: RoleLibraryJob[] },
  );
  if (loaded && Array.isArray(loaded.jobs)) return loaded;
  console.warn("[role-library] could not find role-library.json");
  return { generated_at: new Date().toISOString(), jobs: [] };
}

// One-time LLM summaries for bundled roles, keyed by job_id. Generated by
// scripts/backfill-role-summaries.ts and committed.
const ROLE_SUMMARIES: Record<string, string> = loadSharedJson(
  "role-summaries.json",
  BUNDLED_SUMMARIES as Record<string, string>,
);

const LIBRARY = loadLibrary();
export const AUGMENTED_LIBRARY = {
  ...LIBRARY,
  jobs: augmentRoleLibrary(LIBRARY.jobs).map((job) => ({
    ...job,
    summary: job.summary ?? ROLE_SUMMARIES[job.job_id],
  })),
};
console.log(
  `[role-library] loaded ${AUGMENTED_LIBRARY.jobs.length} jobs (generated ${AUGMENTED_LIBRARY.generated_at})`,
);

const INTERNAL_JOB_IDS = new Set(["internal-business-architect"]);

export interface CombinedLibrary {
  generated_at: string;
  jobs: RoleLibraryJob[];
  bundled_count: number;
  synced_count: number;
  synced_active_count: number;
}

// The combined library merges the bundled (historical) snapshot with EVERY
// synced role — active or not. Roles that drop off the Greenhouse feed stay
// in the library forever; isActive is carried as pure metadata (is_active).
// Deduped by job_id; bundled roles win on ID conflict so historical context
// is preserved exactly as-shipped.
let libraryCache: CombinedLibrary | null = null;
let digestCache: string | null = null;

export function invalidateRoleLibraryCache(): void {
  libraryCache = null;
  digestCache = null;
}

export async function getCombinedLibrary(): Promise<CombinedLibrary> {
  if (libraryCache) return libraryCache;
  const synced = await storage.listSyncedRoles(false);
  const activeIds = new Set(
    synced.filter((r) => r.isActive === 1).map((r) => r.jobId),
  );
  const bundledIds = new Set(
    AUGMENTED_LIBRARY.jobs.map((j) => j.job_id).filter(Boolean),
  );
  const additions: RoleLibraryJob[] = [];
  for (const row of synced) {
    if (bundledIds.has(row.jobId)) continue;
    additions.push({
      ...syncedRoleToLibraryJob(row),
      is_active: row.isActive === 1,
    });
  }
  // listSyncedRoles has no ORDER BY — sort so the library (and therefore the
  // digest and the cached matching prompt) is byte-stable between calls.
  additions.sort((a, b) => (a.job_id < b.job_id ? -1 : a.job_id > b.job_id ? 1 : 0));
  const bundled = AUGMENTED_LIBRARY.jobs.map((job) => ({
    ...job,
    is_active: INTERNAL_JOB_IDS.has(job.job_id)
      ? undefined
      : activeIds.has(job.job_id),
  }));
  libraryCache = {
    generated_at: AUGMENTED_LIBRARY.generated_at,
    jobs: [...bundled, ...additions],
    bundled_count: AUGMENTED_LIBRARY.jobs.length,
    synced_count: additions.length,
    synced_active_count: additions.filter((j) => j.is_active).length,
  };
  return libraryCache;
}

export async function getLibraryDigest(): Promise<string> {
  if (digestCache !== null) return digestCache;
  const lib = await getCombinedLibrary();
  digestCache = buildLibraryDigest(lib.jobs);
  return digestCache;
}

/* ----------------- Digest ----------------- */

// Must match the department names in the matcher-llm taxonomy prompt.
const TAXONOMY_DEPARTMENTS = [
  "Data Engineering",
  "Analytics",
  "Machine Learning",
  "Advisory",
  "Business Architecture",
  "Managed Services",
  "PMO",
  "Sales",
];

// Greenhouse department names that differ from the taxonomy names.
const DEPT_ALIASES: Record<string, string> = {
  "program management office (pmo)": "PMO",
  "program management office": "PMO",
  "ml & ai": "Machine Learning",
  "machine learning & ai": "Machine Learning",
};

function canonicalDepartment(raw: string): string | null {
  const trimmed = raw.trim().toLowerCase();
  const exact = TAXONOMY_DEPARTMENTS.find((d) => d.toLowerCase() === trimmed);
  if (exact) return exact;
  return DEPT_ALIASES[trimmed] ?? null;
}

// Deterministic fallback line for roles that don't have a stored LLM summary
// (e.g. the summary call failed during a sync). Built purely from structured
// fields so the digest stays byte-stable.
function fallbackSummaryLine(job: RoleLibraryJob): string {
  const parts: string[] = [];
  const opener = job.seniority ? `${job.seniority}-level role` : "Role";
  parts.push(
    job.required_yoe != null
      ? `${opener} requiring ${job.required_yoe}+ years of experience.`
      : `${opener}.`,
  );
  if (job.required_skills.length > 0) {
    parts.push(`Key skills: ${job.required_skills.slice(0, 8).join(", ")}.`);
  }
  if (job.preferred_skills.length > 0) {
    parts.push(`Preferred: ${job.preferred_skills.slice(0, 5).join(", ")}.`);
  }
  return parts.join(" ");
}

interface DigestEntry {
  title: string;
  current: boolean;
  summary: string;
}

// Pure + deterministic: fixed department order, sorted titles, no timestamps
// Hard ceiling on how much of a stored summary the digest will carry. The
// digest is paid per candidate in batch runs, so a runaway summary must not
// be able to silently inflate every request. Deterministic truncation.
const MAX_DIGEST_SUMMARY_CHARS = 220;

function capSummary(text: string): string {
  return text.length > MAX_DIGEST_SUMMARY_CHARS
    ? `${text.slice(0, MAX_DIGEST_SUMMARY_CHARS - 1)}…`
    : text;
}

// or counts. The string only changes when the library genuinely changes, so
// the cached matching system prompt is only rebuilt after a real sync change.
export function buildLibraryDigest(jobs: RoleLibraryJob[]): string {
  const taxonomyEntries = new Map<string, Map<string, DigestEntry>>();
  const otherEntries = new Map<string, Map<string, DigestEntry>>();

  for (const job of jobs) {
    if (!job.title) continue;
    const canonical = canonicalDepartment(job.department);
    const bucket = canonical
      ? taxonomyEntries
      : otherEntries;
    const deptKey = canonical ?? job.department.trim();
    if (!deptKey) continue;
    let titles = bucket.get(deptKey);
    if (!titles) {
      titles = new Map();
      bucket.set(deptKey, titles);
    }
    const current = job.is_active !== false;
    const summary = capSummary(job.summary?.trim() || fallbackSummaryLine(job));
    const existing = titles.get(job.title);
    if (!existing) {
      titles.set(job.title, { title: job.title, current, summary });
    } else {
      // A title counts as current if ANY posting with it is current, and a
      // current posting's summary wins over a historical one's.
      if (current && !existing.current) {
        existing.current = true;
        existing.summary = summary;
      }
    }
  }

  // Inactive roles can never be routed to — the model only needs to know the
  // title existed, so their summary lines are dead weight paid on every
  // candidate. Titles-only for historical entries; active entries keep their
  // (220-char-capped) summary. Stored summaries are untouched — this changes
  // rendering only, so a reactivated role gets its summary line back for free.
  const renderEntries = (titles: Map<string, DigestEntry>): string[] =>
    Array.from(titles.values())
      .sort((a, b) => (a.title < b.title ? -1 : a.title > b.title ? 1 : 0))
      .map((e) =>
        e.current
          ? `- ${e.title}: ${e.summary}`
          : `- ${e.title} (no longer posted)`,
      );

  const sections: string[] = [
    `## phData Role Library — actual roles phData has hired for (supplementary context)

Real phData job postings, grouped by department. Active roles include a summary of responsibilities and qualifications; roles marked "(no longer posted)" are historical titles that remain valid evidence of the kind of work each department does. This list is SUPPLEMENTARY — the department definitions above are authoritative, and your output must still be one of the valid department values listed below.`,
  ];

  for (const dept of TAXONOMY_DEPARTMENTS) {
    const titles = taxonomyEntries.get(dept);
    if (!titles || titles.size === 0) continue;
    sections.push(`### ${dept}\n${renderEntries(titles).join("\n")}`);
  }

  if (otherEntries.size > 0) {
    const otherLines: string[] = [
      "### Other posted departments (map candidates to the closest department above; do not output these names)",
    ];
    for (const dept of Array.from(otherEntries.keys()).sort()) {
      otherLines.push(`${dept}:`);
      otherLines.push(...renderEntries(otherEntries.get(dept)!));
    }
    sections.push(otherLines.join("\n"));
  }

  return sections.join("\n\n");
}
